StoreStockingSystemWebsite/Models/Store.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PCDSWebsite.Models
{
    public class Store
    {
        public string Name { get; set; }
        public string SalesStatus { get; set; } //Used for mocking
        public List<Stock> StockList { get; set; }
        public string StockStatus { get; set; } //Used for mocking
        public int HistoricSalesSpeed { get; set; } //Used for mocking
        public int CurrentSalesSpeed { get; set; } //Used for mocking
        public string SalesTendency { get; set; } //Used for mocking
        public string ExpectedSalesReachedPercentage { get; set; }  //Used for mocking
    }
}

StoreStockingSystemWebsite/Models/StoreViewModel.cs
using System.Collections.Generic;
using StoreStockingSystem.Models;

namespace PCDSWebsite.Models
{
    public class StoreViewModel
    {
        public StoreStockingSystem.Models.Store Store { get; set; }
        public List<StoreStockingSystem.Models.Stock> Stocks { get; set; }
        public PerformanceDetail Performance { get; set; }
    }
}

StoreStockingSystemWebsite/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PCDSWebsite.Models;
using StoreStockingSystem.Services;
using Stock = StoreStockingSystem.Models.Stock;

namespace PCDSWebsite.Controllers
{
    public class StoresController : Controller
    {
        public ActionResult Index()
        {
            var model = StoreService.GetStores();

            return this.View(model);
        }

        [HttpGet]
        public ActionResult StoreDetails(int id = 0)
        {
            var store = StoreService.GetStore(id);
            var stocks = StockService.GetStocks(store);
            var storePerformance = SalesService.GetStorePerformanceDetails(id);

            var model = new StoreViewModel
            {
                Store = store,
                Stocks = stocks,
                Performance = storePerformance
            };

            return View(model);
        }

        public ActionResult ChainDetails(DateTime startTime, DateTime endTime, int id = 0)
        {
            var chain = ChainService.GetChain(id);
            var stores = ChainService.GetChainStores(id);
            var performance = ChainPerformance(startTime, endTime, id);


            var model = new ChainViewModel
            {
                Chain = chain,
                Stores = stores,
                Performance = performance
            };

            return View(model);
        }

        public ChainPerformanceModel ChainPerformance(DateTime startTime, DateTime endTime, int id = 0)
        {

            var values = SalesService.GetMonthlyChainPerformance(id, startTime, endTime, null);
            var accValues = SalesService.GetAccumMonthlyChainPerformance(id, startTime, endTime, null);
            var total = SalesService.GetChainPerformance(id, startTime, endTime, null);
            var chainPerformance = new ChainPerformanceModel
            {
                StartTime = startTime,
                EndTime = endTime,
                Values = values,
                AccPerValues = accValues,
                TotalSales = total

            };


            return chainPerformance;
        }

        public ActionResult ChainsOverview()
        {
            var model = ChainService.GetChains();

            return View(model);
        }

        public ActionResult StockList()
        {
            var model = new List<StockRefillWebModel>();

            var stocks = StockService.GetStocksNeedingRefilling();

            foreach (var stock in stocks)
            {
                var stockMissing = 0;

                foreach (var productStock in stock.ProductStocks)
                {
                    if (productStock.CurrentAmount >= 0 && productStock.Capacity >= productStock.CurrentAmount)
                    {
                        stockMissing += productStock.Capacity - productStock.CurrentAmount;
                    }
                    else
                    {
                        stockMissing += productStock.Capacity + Math.Abs(productStock.CurrentAmount);
                    }
                }

                model.Add(new StockRefillWebModel
                {
                    StockId = stock.Id,
                    StoreName = stock.Store.Name,
                    StockMissing = stockMissing,
                    SelectedForRefilling = false
                });
            }

            return View(model);
        }

        [HttpPost] //TODO: Refactor this method, was completed in a hurry before sprint end.
        public void StockList(List<StockRefillWebModel> stocks)
        {
            //var productsRefill = new List<RefillEntry>(); //TODO: Refactor into seperate class. Currently holds a tuple <product, displayType, amountToBringForRefill>

            //foreach (var stock in stocks)
            //{
            //    foreach (var productStock in stock.ProductStocks)
            //    {
            //        if (productStock.CurrentAmount < productStock.Capacity)
            //        {
            //            var productMissing = 0;

            //            if (productStock.CurrentAmount >= 0 && productStock.Capacity >= productStock.CurrentAmount)
            //            {
            //                productMissing = productStock.Capacity - productStock.CurrentAmount;
            //            }
            //            else
            //            {
            //                productMissing = productStock.Capacity + Math.Abs(productStock.CurrentAmount);
            //            }

            //            var refillEntry = productsRefill.FirstOrDefault(p => p.Product.Id == productStock.Product.Id && p.DisplayType.Id == stock.DisplayTypeId);

            //            if (refillEntry == null)
            //            {
            //                productsRefill.Add(new RefillEntry
            //                {
            //                    Product = productStock.Product,
            //                    DisplayType = stock.DisplayType,
            //                    RefillCount = productMissing
            //                });
            //            }
            //            else
            //            {
            //                refillEntry.RefillCount += productMissing;
            //            }
            //        }
            //    }
            //}

            Refill(new List<RefillEntry>());
        }

        public ActionResult Refill(List<RefillEntry> stocksToRefill)
        {
            var stocks = StockService.GetStocksNeedingRefilling();

            var random = new Random();
            stocks = stocks.OrderBy(item => random.Next()).ToList();

            while (stocks.Count > 3)
            {
                var stock = stocks.First();

                stocks.Remove(stock);
            }

            var productsDict = new Dictionary<string, RefillEntry>();

            foreach (var stock in stocks)
            {
                foreach (var ps in stock.ProductStocks)
                {
                    if (productsDict.ContainsKey(ps.Product.Name))
                    {
                        productsDict[ps.Product.Name].RefillCount += ps.Capacity - ps.CurrentAmount;
                    }
                    else
                    {
                        productsDict[ps.Product.Name] = new RefillEntry
                        {
                            DisplayType = stock.DisplayType,
                            Product = ps.Product,
                            RefillCount = ps.Capacity - ps.CurrentAmount,
                        };
                    }
                }
            }

            return View(productsDict.Values.ToList().OrderByDescending(l => l.RefillCount).ToList());
        }

        public ActionResult Alerts()
        {
            return View();
        }

        public ActionResult StockUpdate()
        {
            return View();
        }
    }
}

StoreStockingSystemWebsite/Views/Stores/Alerts.cshtml
@{
    ViewBag.Title = "StoreDataList";
}
@section scripts
{
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables-1.10.5/media/css/jquery.dataTables.css">

    <!-- jQuery -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.js"></script>

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready(function () {
            $('#stores-table').DataTable();
        });

    </script>
}

<h2>Stores</h2>

<table id="stores-table" class="display" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Sales Status</th>
            <th>Stock Status</th>
            <th>Sales tendency</th>
            <th>Expected sales reached this year</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td style="background-color:greenyellow">Fona Amager</td>
            <td style="background-color:greenyellow">Ok (102% of expected)</td>
            <td style="background-color:greenyellow">Ok (20 days left)</td>
            <td style="background-color:greenyellow">Rising</td>
            <td style="background-color: greenyellow">120%</td>
            <td style="display:none">Some Store ID</td>
            <td style="background-color:greenyellow">@Html.ActionLink("See more", "StorePerformanceDetails", new {id = 99})</td>
</tr>
        
        <tr>
            <td style="background-color:greenyellow">Fona Odense</td>
            <td style="background-color:greenyellow">Ok (105% of expected)</td>
            <td style="background-color:greenyellow">Ok (15 days left)</td>
            <td style="background-color:greenyellow">Steady</td>
            <td style="background-color:greenyellow">106%</td>
            <td style="background-color:greenyellow">@Html.ActionLink("See more", "StorePerformanceDetails")</td>
        </tr>
        
        <tr>
            <td style="background-color:greenyellow">Fona Svendborg</td>
            <td style="background-color:greenyellow">Ok (97% of expected)</td>
            <td style="background-color:greenyellow">Ok (27 days left)</td>
            <td style="background-color:greenyellow">Rising</td>
            <td style="background-color:greenyellow">98%</td>
            <td style="background-color:greenyellow">@Html.ActionLink("See more", "StorePerformanceDetails")</td>
        </tr>

        <tr>
            <td style="background-color:yellow">Føtex Frederiksberg</td>
            <td style="background-color:yellow">Ok (95% of expected)</td>
            <td style="background-color:yellow">Running out (4 days left)</td>
            <td style="background-color:yellow">Rising</td>
            <td style="background-color:yellow">97%</td>
            <td style="background-color:yellow">@Html.ActionLink("See more", "StorePerformanceDetails")</td>
        </tr>

        <tr>
            <td style="background-color:red">Bog & Idé Holbæk</td>
            <td style="background-color:red">Bad (62% of expected)</td>
            <td style="background-color:red">Out of stock (0 days left)</td>
            <td style="background-color:red">Falling</td>
            <td style="background-color:red">60%</td>
            <td style="background-color:red">@Html.ActionLink("See more", "StorePerformanceDetails")</td>
        </tr>
    </tbody>
</table>

StoreStockingSystemWebsite/Views/Stores/ChainDetails.cshtml
@using System.Data.Entity.Core.Metadata.Edm
@using Microsoft.Ajax.Utilities
@model PCDSWebsite.Models.ChainViewModel

@{
    ViewBag.Title = "Chain Performance";
}

<!DOCTYPE html>

<html>
<head>
    <title>ViewBag.Title</title>

</head>
<body>
    <h3>@Model.Chain.Name</h3>
    <b>Number of Chain stores: @Model.Stores.Count</b>
    <br />

    <hr />
    <table>
        <tr>
            <td style="text-align: left; vertical-align: top; padding: 0">

                @using (Html.BeginForm("ChainDetails", "Stores", FormMethod.Post))
                {

                    <h4>Period</h4>
                    <input type="text" id="startTime" name="startTime" value=@Model.Performance.StartTime>
                    <br />
                    <input type="text" id="endTime" name="endTime" value=@Model.Performance.EndTime>
                    <br />
                    <input type="submit" value="Get Performance" />
                }

                <hr />
                <h4>Totel period sales</h4>
                <b>@Model.Performance.TotalSales</b>
                @*<h4>Include Expected Sales Numbers</h4>
                    <input type="radio" name="sex" value="male">Yes <input type="radio" name="sex" value="female">No*@
                <hr />
                @*<h4>Include Historic Sales Numbers</h4>
                    <input type="radio" name="sex" value="male">Yes <input type="radio" name="sex" value="female">No*@
            </td>

            <td width="100%">
                <div id="performancegraph"></div>
            </td>

        </tr>
    </table>
    <hr />

    <h4>Chain Stores</h4>
    <table id="chainstores-table" class="display" width="100%">
        <thead>
            <tr>
                <th>Store Id</th>
                <th>Store Name</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var store in Model.Stores)
            {
                <tr>
                    <td>@store.Id</td>

                    <td>@store.Name</td>

                    <td>
                        @Html.ActionLink("Details", "StoreDetails", new { store.Id })
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <hr />
</body>
</html>

@section scripts
{
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables-1.10.5/media/css/jquery.dataTables.css">
    <!-- jQuery -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.js"></script>
    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.dataTables.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

    <script>
        $(document).ready(function () {
            $('#performance-table').DataTable();
            $('#chainstores-table').DataTable();
        });

    </script>

    <script type="text/javascript" charset="utf8" src="~/Scripts/highcharts.js"></script>
    <script>
        $(function () {
            var actualSales = [];
            var accSales = [];

            @foreach (decimal actualSale in Model.Performance.Values)
            {
                @:actualSales.push(@actualSale);
            }

            for (var i = 0; i < actualSales.length; i++) {
                if (actualSales[i] === 0) {
                    actualSales.splice(i, 1);
                }
            }

            @foreach (var accSale in Model.Performance.AccPerValues)
            {
                @:console.log("Adding")
                @:console.log(@decimal.ToInt32(accSale))
                @:accSales.push(@accSale);
                        }

            for (var i = 0; i < accSales.length; i++) {
                if (accSales[i] === 0) {
                    accSales.splice(i, 1);
                }
            }

            $('#performancegraph').highcharts({
                title: {
                    text: 'Chain Performance',
                    x: -20 //center
                },
                xAxis: {
                    categories: [
                        'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
                    ]
                },
                yAxis: {
                    title: {
                        text: 'Sales amount'
                    },
                    plotLines: [
                        {
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }
                    ]
                },
                tooltip: {
                    valueSuffix: 'Kr'
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth: 0
                },
                series: [
                    {
                        name: 'Actual sales',
                        type: 'column',
                        data: actualSales
                    }
                ,
                    {
                        name: 'Accumulated sales',
                        type: 'line',
                        data: accSales
                    }]
            });
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $('#startTime').datepicker({ dateFormat: "dd-mm-yy" });
            $('#endTime').datepicker({ dateFormat: "dd-mm-yy" });
        });
    </script>

}

StoreStockingSystemWebsite/Views/Stores/ChainsOverview.cshtml
@model IEnumerable<Chain>

@using PCDSWebsite.Models
@using Chain = StoreStockingSystem.Models.Chain

@{
    ViewBag.Title = "Chains";
}

<!DOCTYPE html>

<html>
<head>
    <title>ViewBag.Title</title>

</head>
<body>
    <h2>Chains</h2>


    <table id="chains-table" class="display" width="100%">
        <thead>
            <tr>
                <th>Chain Id</th>
                <th>Chain Name</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var chain in Model)
            {
                <tr>
                    <td>@chain.Id</td>

                    <td>@chain.Name</td>

                    <td>
                        @Html.ActionLink("Details", "ChainDetails", new { chain.Id, startTime = new DateTime(DateTime.Now.Year, 1, 1), endTime = new DateTime(DateTime.Now.Year, 12, 31) })
                    </td>

                </tr>
            }
        </tbody>
    </table>
</body>
</html>

@section scripts
{
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables-1.10.5/media/css/jquery.dataTables.css">

    <!-- jQuery -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.js"></script>

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready(function () {
            $("#chains-table").DataTable();
        });

    </script>
}

StoreStockingSystemWebsite/Views/Stores/ChannelsPerformance.cshtml
@{
    ViewBag.Title = "Store Performance";
}
@section scripts
{
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables-1.10.5/media/css/jquery.dataTables.css">
    <!-- jQuery -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.js"></script>
    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.dataTables.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

    <script>
        $(document).ready(function () {
            $('#performance-table').DataTable();
        });

    </script>
    

    <script type="text/javascript" charset="utf8" src="~/Scripts/highcharts.js"></script>
    <script>
        $(function () {
            $('#container').highcharts({
                title: {
                    text: 'Monthly sales',
                    x: -20 //center
                },
                xAxis: {
                    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                },
                yAxis: {
                    title: {
                        text: 'Sales amount'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    valueSuffix: 'Kr'
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle',
                    borderWidth: 0
                },
                series: [{
                    name: 'Salg 2012',
                    data: [1578, 1035, 1950, 2530, 3400, 3399, 4585, 4500, 3800, 6500, 15300, 35000]
                }, {
                    name: 'Salg 2013',
                    data: [4050, 4535, 3750, 6530, 6400, 4399, 0, 5500, 6800, 8500, 19300, 45000]
                }, {
                    name: 'Salg 2014',
                    data: [5700, 6535, 6750, 3530, 8400, 2399, 4585, 9500, 2800, 9500, 24300, 85000]
                }, {
                    name: 'Salg 2015',
                    data: [8700, 15535, 12750]
                }]
            });
        });
    </script>
    
    <script type="text/javascript">
        $(function () {
            $('#startdate').datepicker({ dateFormat: "dd-mm-yy" });
            $('#enddate').datepicker({ dateFormat: "dd-mm-yy" });
        });
    </script>
    
}

<h3>Overall Retail Channel Performance</h3>


<hr/>
<table>
    <tr>
        <td style="text-align:left;vertical-align:top;padding:0">
            <h4>Dates</h4>
            <input type="text" id="startdate" name="startdate" value="Start date"><br/><br/>
            <input type="text" id="enddate" name="enddate" value="End date">
            <hr/>
            <h4>Retail Channels</h4>
            <div class="container" style="border: 1px solid #ccc; width: 200px; height: 130px; overflow-y: scroll;">
                <input type="checkbox" /> Fona<br />
                <input type="checkbox" /> Føtex<br />
                <input type="checkbox" /> Bog & Idé<br />
                <input type="checkbox" /> ...<br />
                <input type="checkbox" /> ...<br />
                <input type="checkbox" /> ...<br />
                <input type="checkbox" /> ...<br />
                <input type="checkbox" /> ...<br />
                <input type="checkbox" /> ...<br />

            </div>
            <hr/>
            <h4>Include Expected Sales Numbers</h4>
            <input type="radio" name="sex" value="male">Yes <input type="radio" name="sex" value="female">No
            <hr/>
            <h4>Include Historic Sales Numbers</h4>
            <input type="radio" name="sex" value="male">Yes <input type="radio" name="sex" value="female">No
        </td>
        <td width="100%">
            <div id="container"></div>
        </td>
    </tr>
</table>
<hr/>

StoreStockingSystemWebsite/Views/Stores/Index.cshtml
@model IEnumerable<Store>

@using System.Activities.Expressions
@using PCDSWebsite.Models
@using StoreStockingSystem.Models
@using StoreStockingSystem.Services;
@using Stock = StoreStockingSystem.Models.Stock
@using Store = StoreStockingSystem.Models.Store

@{
    ViewBag.Title = "Stores";
}

<!DOCTYPE html>

<html>
<head>
    <title>ViewBag.Title</title>

</head>
<body>
    <h2>Stores</h2>


    <table id="stores-table" class="display" width="100%">
        <thead>
            <tr>
                <th>Store Id</th>
                <th>Store Name</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var store in Model)
            {
                <tr>
                    <td>@store.Id</td>

                    <td>@store.Name</td>

                    <td>
                        @Html.ActionLink("Details", "StoreDetails", new { store.Id })
                    </td>

                </tr>
            }
        </tbody>
    </table>
</body>
</html>

@section scripts
{
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="~/Scripts/DataTables-1.10.5/media/css/jquery.dataTables.css">

    <!-- jQuery -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.js"></script>

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables-1.10.5/media/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready(function () {
            $("#stores-table").DataTable();
        });

    </script>
}

StoreStockingSystemWebsite/Views/Stores/Refill.cshtml
@model List<PCDSWebsite.Models.RefillEntry>

@{
    ViewBag.Title = "Critial Stores";
}

<!DOCTYPE html>

<html>
<head>
    <title>Store Refill</title>
</head>
<body>
    <h1>Store refill run</h1>
    <table class="display" style="width: 100%;">
        <thead>
            <tr>
                <th>Display Type</th>
                <th>Product Name</th>
                <th>Count to pack</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var refillEntry in Model)
            {
                <tr class="critical">
                    <td>@refillEntry.DisplayType.Name</td>
                    <td>@refillEntry.Product.Name</td>
                    <td>@refillEntry.RefillCount</td>
                </tr>
            }
        </tbody>
    </table>

    <h3>Store locations</h3>
    <table style="width: 100%;">
        <tr>
            <td>
                <div id="map" style="width: 500px; height: 400px; vertical-align: top; float: left;"></div>
            </td>
            <!--Right side of map area-->
            <td style="vertical-align: top">
                <table style="width: 100%;">
                    <tr><td colspan="2"><h4>Waypoints</h4></td></tr>

                    <tr>
                        <td colspan="2">
                            <div id="directions_panel" style="margin: 20px; background-color: #FFEE77;"></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div id="totalDuration" style="background-color: orange;"></div>
                            <div id="totalDistance" style="background-color: orange;"></div>
                        </td>
                    </tr>
                </table>
    </table>
</body>
</html>

<!--Loading google maps javascript api with our api key-->
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDFZQo4FYhLzLW9FIwKmbO235mRDg6n2kM&sensor=false">

</script>
<!--Google Maps stuff-->
<script type="text/javascript">
    google.maps.event.addDomListener(window, "load", initialize);

    // Route calculation
    var directionsService;
    var directionsDisplay;
    var map;

    function initialize() {
        directionsService = new google.maps.DirectionsService();
        directionsDisplay = new google.maps.DirectionsRenderer();
        var copenhagen = new google.maps.LatLng(55.6712673, 12.5608388);
        var mapOptions = {
            zoom: 6,
            center: copenhagen
        }
        map = new google.maps.Map(document.getElementById('map'), mapOptions);
        directionsDisplay.setMap(map);

        console.log("Calling route");
        calcRoute();
    }


    // Calculation function
    function calcRoute() {
        var start = 'Sortedams Dossering 55, 2100 København Ø, Denmark';
        var end = 'Sortedams Dossering 55, 2100 København Ø, Denmark';

        var waypts = [];

        waypts.push({ location: "FONA Trianglen, Østerbrogade 62, 2100 København Ø, Denmark" });
        waypts.push({ location: 'FONA, Nørre Voldgade 17, 1358 København K, Denmark' });
        waypts.push({ location: 'FONA Strøget, Østergade 47, 1100 København K, Denmark' });

        var request = {
            origin: start,
            destination: end,
            waypoints: waypts,
            optimizeWaypoints: true,
            travelMode: google.maps.TravelMode.DRIVING
        };


        directionsService.route(request, function (response, status) {
            console.log("getting route");
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
                var route = response.routes[0];
                var summaryPanel = document.getElementById('directions_panel');
                summaryPanel.innerHTML = '';
                var duration = 0;
                var distance = 0;
                for (var i = 0; i < route.legs.length; i++) {
                    var routeSegment = i + 1;
                    // Summarize duration & distance
                    duration += route.legs[i].duration.value;
                    distance += route.legs[i].distance.value;


                    summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment + '</b><br>';
                    summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
                    summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                    summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                }
                // Set total duration and distance fields
                var totalDur = document.getElementById('totalDuration');
                totalDur.innerHTML = '<b>Total duration: ' + duration / 60 + ' minutes</b>';
                var totalDist = document.getElementById('totalDistance');
                totalDist.innerHTML = '<b>Total distance: ' + distance / 1000 + ' km</b>';
            }

        });
    }
</script>

<!--Google Maps route calculation-->
@*var addresses = [
    ['FONA Trianglen, Østerbrogade 62, 2100 København Ø, Denmark'],
    ['FONA, Nørre Voldgade 17, 1358 København K, Denmark'],
    ['FONA Strøget, Østergade 47, 1100 København K, Denmark'],
    ['FONA, Nørrebro Bycenter, Lygten 2, 2400 København NV'],
    ['FONA Amager Centret, Amager Centret 136, 2300 København S, Denmark'],
    ['FONA, Nørrebro Bycenter, Lygten 2, 2400 København NV']
    ];*@